private _zsn_list = _this;
private _zsn_units = [];
{_zsn_units pushback _x} foreach _zsn_list;
["", "BLACK OUT"] remoteexec ["titleText", _zsn_units];
private _zsn_ranked = _zsn_units apply {[rankId _x, rating _x, _x]};
_zsn_ranked = _zsn_ranked - [ -1 ];
_zsn_ranked sort false;
private _hr = _zsn_ranked select 0 select 2;
private _grp = createGroup east;
{[_x select 2] joinsilent _grp} forEach _zsn_ranked;
_hr setUnitRank "SERGEANT";
if (count _zsn_units > 1) then {_zsn_ranked select 1 select 2 setUnitRank "CORPORAL"; _zsn_ranked select 1 select 2 assignteam "YELLOW";};
if (count _zsn_units > 2) then {_zsn_ranked select 2 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 2 select 2 assignteam "BLUE";};
if (count _zsn_units > 3) then {_zsn_ranked select 3 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 3 select 2 assignteam "YELLOW";};
if (count _zsn_units > 4) then {_zsn_ranked select 4 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 4 select 2 assignteam "BLUE";};
if (count _zsn_units > 5) then {_zsn_ranked select 5 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 5 select 2 assignteam "YELLOW";};
if (count _zsn_units > 6) then {_zsn_ranked select 6 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 6 select 2 assignteam "BLUE";};
if (count _zsn_units > 7) then {_zsn_ranked select 7 select 2 setUnitRank "PRIVATE"; _zsn_ranked select 7 select 2 assignteam "YELLOW";};
if (count _zsn_units > 8) then {_zsn_ranked select 8 select 2 setUnitRank "CORPORAL"; _zsn_ranked select 8 select 2 assignteam "BLUE";};
if (count _zsn_units > 9) then {_zsn_ranked select 9 select 2 setUnitTrait ["Medic",true]; _zsn_ranked select 9 select 2 assignteam "RED";};
if (zsn_loe) then {
	[_hr, zsn_eloadouts select 0] call zsn_fnc_loadInventory;
	if (count _zsn_units > 1) then {[_zsn_ranked select 1 select 2, zsn_eloadouts select 1] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 2) then {[_zsn_ranked select 2 select 2, zsn_eloadouts select 2] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 3) then {[_zsn_ranked select 3 select 2, zsn_eloadouts select 3] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 4) then {[_zsn_ranked select 4 select 2, zsn_eloadouts select 4] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 5) then {[_zsn_ranked select 5 select 2, zsn_eloadouts select 5] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 6) then {[_zsn_ranked select 6 select 2, zsn_eloadouts select 6] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 7) then {[_zsn_ranked select 7 select 2, zsn_eloadouts select 7] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 8) then {[_zsn_ranked select 8 select 2, zsn_eloadouts select 8] call zsn_fnc_loadInventory;};
	if (count _zsn_units > 9) then {[_zsn_ranked select 9 select 2, zsn_eloadouts select 9] call zsn_fnc_loadInventory;};
};
{_x setVehiclePosition [(getpos zsn_respawn_east), [], 8];} forEach _zsn_units;
[format ["New squad spawned, callsign %2. %1 is the the squad leader", name _hr, _grp]] remoteExec ["hintSilent", east];
[_zsn_units] remoteexec ["zsn_fnc_newwave"];
